module.exports = {
  ADD_COMPONENT: "ADD_COMPONENT",
  ADD_CHILD_COMPONENT: "ADD_CHILD_COMPONENT",
  DELETE_COMPONENT: "DELETE_COMPONENT",
  CLEAR_COMPONENTS: "CLEAR_COMPONENTS",
  SELECT_COMPONENT: "SELECT_COMPONENT",
  UPDATE_SELECTED_COMPONENT: "UPDATE_SELECTED_COMPONENT",
  MOVE_COMPONENT: "MOVE_COMPONENT"
};